name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBE
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6JuvYDZgOoI83Qp9A8oEQQ"
          
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEETUP
          feed_list: "http://feeds.feedburner.com/Events-netVale"
